language: python
# See: https://docs.djangoproject.com/en/1.9/faq/install/#what-python-version-can-i-use-with-django
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
install:
  - pip install tox tox-travis
script:
  - tox
